# This creates the demonstration utility "lguest" which runs a Linux guest.
# Missing headers?  Add "-I../../../include -I../../../arch/x86/include"
CFLAGS:=-m32 -O3 -U_FORTIFY_SOURCE

all: lguest

clean:
	rm -f lguest
